[test]
minimum_drhodz = 0.02

[cwa]
minimum_drhodz = 0.02

[ozroms-daily]
minimum_drhodz = 0.01

[DEFAULT]
# --- for transect creation ---
transect_contours = [10.0, 20.0, 30.0, 40.0, 50.0, 60.0, 70.0, 80.0, 90.0, 100.0, 120.0, 140.0, 160.0, 180.0, 200.0]
angle_tolerance = 45.0 # in degrees, if the angle between two contour lines is larger than this, a mean value is taken
max_distance_contours = 100000.0 # in m, max distance at which next contour line is crossed, increasing this decreases accuracy of intersections

# --- for dswt detection ---
drhodz_depth_percentage = 0.3
minimum_percentage_consecutive_cells = 0.1
filter_depth = 100.0
dswt_cross_shelf_transport_depth_range = [50.0, 60.0]
# minimum_drhodz NO DEFAULT

# --- for transport calculation (optional) ---
cross_shelf_transport_depth = 55.0
cross_shelf_bottom_layers_percentage = 0.15
cross_shelf_surface_layers_percentage = 0.15
cross_shelf_interior_layers_percentage = 0.7 # remaining after surface and bottom
